spring:
  application:
    name: backend
  datasource:
    url: jdbc:mysql://rm-cn-9me4964qo001148o.rwlb.rds.aliyuncs.com:3306/breeze-tribe
    username: root
    password: H2v4uZwDpBVv4ysHy5wy
    driver-class-name: com.mysql.cj.jdbc.Driver
  #    url: jdbc:mysql://localhost:3306/breeze-tribe
  #    username: root
  #    password: 95515
  #    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: false # 是否在控制台显示Hibernate执行的SQL语句
    hibernate:
      ddl-auto: update # 开发和测试阶段，'update' 比较方便
    properties:
      hibernate:
        format_sql: true

  jwt:
    secret: ThereisnofuturethereisnopastThankGodthismomentisnotthelast
    expiration: 72000000 # 20h，单位毫秒

  mail:
    host: smtp.qq.com
    port: 587
    username: 2365246549@qq.com       # 你的QQ邮箱账号
    password: ykauwqrvjrewebgj  # 你刚才生成的授权码
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true
          ssl.enable: false  # 587端口一般不启用SSL
  data:
    redis:
      host: 121.43.136.251
      #host: localhost
      port: 6379
      password: cloudora100points
      database: 0

baidu:
  map:
    ak: cX3Lu6F9cEcRr7M2K80G0Di49wvz4hY0

#Sms
sms:
  host: https://gyytz.market.alicloudapi.com
  path: /sms/smsSend
  method: POST
  appcode: 37d5da8d351c43fea103145f51e4d64c
  smsSignId: 2e65b1bb3d054466b82f0c9d125465e2
  templateId: 908e94ccf08b4476ba6c876d13f084ad