spring:
  application:
    name: backend
  datasource:
    url: jdbc:mysql://rm-cn-9me4964qo001148o.rwlb.rds.aliyuncs.com:3306/breeze-tribe
    username: root
    password: H2v4uZwDpBVv4ysHy5wy
    driver-class-name: com.mysql.cj.jdbc.Driver
  #    url: jdbc:mysql://localhost:3306/breeze-tribe
  #    username: root
  #    password: 95515
  #    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: false # 是否在控制台显示Hibernate执行的SQL语句
    hibernate:
      ddl-auto: update # 开发和测试阶段，'update' 比较方便
    properties:
      hibernate:
        format_sql: true
  servlet:
    multipart:
      max-file-size: 8MB
      max-request-size: 64MB

  jwt:
    secret: ThereisnofuturethereisnopastThankGodthismomentisnotthelast
    #expiration: 3600000 # 1h，单位毫秒
    expiration: 20000 # 20s，单位毫秒

  mail:
    host: smtp.qq.com
    port: 587
    username: 2365246549@qq.com       # 你的QQ邮箱账号
    password: ykauwqrvjrewebgj  # 你刚才生成的授权码
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true
          ssl.enable: false  # 587端口一般不启用SSL
  data:
    redis:
      host: 121.43.136.251
      #host: localhost
      port: 6379
      password: cloudora100points
      database: 0
      repositories:
        enabled: false

# 服务器配置
server:
  address: 127.0.0.1   # 确保只监听本地回环地址
  port: 8081           # 将 Spring Boot 应用的监听端口改为 8081 (HTTP)
  forward-headers-strategy: FRAMEWORK # 正确推断出API的公共访问URL的协议（https）、主机和端口

ai:
  studio:
    api:
      base-url: https://api-16cddcc9j7rci6vb.aistudio-app.com/v1
      key: df113a1f8c4d874fe44b284c82a5b39a774204b2
    model:
      name: DeepSeek-R1-Distill-Llama-8B-F16

dashscope:
  api-key: sk-98e1d9b45e064da1a03e214f7c0ff468
  app-id: a3a0b11cce024d7b8325632b2cab6924

recommendation:
  weights:
    order: 10
    favorite: 5
    like: 3
    view: 1

baidu:
  map:
    ak: cX3Lu6F9cEcRr7M2K80G0Di49wvz4hY0
#    ak: r49IueXKnldrFS4IWoqnlW0iM1GD77KE



#Sms
sms:
  host: https://gyytz.market.alicloudapi.com
  path: /sms/smsSend
  method: POST
  appcode: aae61b6883c6461a8a50da193577b818
  smsSignId: 2e65b1bb3d054466b82f0c9d125465e2
  templateId: 908e94ccf08b4476ba6c876d13f084ad

#devtools:
#  restart:
#    enabled: false